// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Delete a todo
    #
    # + return - returns can be any of following types
    # http:NoContent (Deleted)
    # http:NotFound (No todo with this id)
    resource function delete todos/[string todoId]() returns http:NoContent|ErrorNotFound {
        boolean deleted = removeTodo(todoId);
        if !deleted {
            return notFoundError(todoId);
        }
        return http:NO_CONTENT;
    }

    # List every todo on the shared list
    #
    # + completed - Filter by completion state
    # + return - A page of todos
    resource function get todos(boolean? completed, int 'limit = 20, int offset = 0) returns inline_response_200 {
        int boundedLimit = 'limit > 100 ? 100 : ('limit < 0 ? 0 : 'limit);
        int boundedOffset = offset < 0 ? 0 : offset;
        TodoPage page = listTodosPage(completed, boundedLimit, boundedOffset);
        return {count: page.count, next: page.next, previous: page.previous, data: page.data};
    }

    # Get one todo
    #
    # + return - returns can be any of following types
    # http:Ok (The todo)
    # http:NotFound (No todo with this id)
    resource function get todos/[string todoId]() returns Todo|ErrorNotFound {
        Todo? todo = findTodo(todoId);
        if todo is () {
            return notFoundError(todoId);
        }
        return todo;
    }

    # Update a todo's title and/or completed state
    #
    # + return - returns can be any of following types
    # http:Ok (The updated todo)
    # http:BadRequest (The title is blank)
    # http:NotFound (No todo with this id)
    resource function patch todos/[string todoId](@http:Payload TodoUpdate payload) returns Todo|ErrorBadRequest|ErrorNotFound {
        string? title = payload?.title;
        if title is string && title.trim().length() == 0 {
            return blankTitleError();
        }
        Todo? updated = applyTodoUpdate(todoId, payload);
        if updated is () {
            return notFoundError(todoId);
        }
        return updated;
    }

    # Create a new todo
    #
    # + return - returns can be any of following types
    # http:Created (The created todo)
    # http:BadRequest (The title is missing or blank)
    resource function post todos(@http:Payload NewTodo payload) returns http:Created|ErrorBadRequest {
        string title = payload.title.trim();
        if title.length() == 0 {
            return blankTitleError();
        }
        Todo created = addTodo(title);
        return <http:Created>{body: created};
    }
}

function notFoundError(string todoId) returns ErrorNotFound {
    Error body = {code: 404, message: "no todo with this id", description: string `No todo found with id ${todoId}`};
    return <ErrorNotFound>{body: body};
}

function blankTitleError() returns ErrorBadRequest {
    Error body = {code: 400, message: "title must not be blank"};
    return <ErrorBadRequest>{body: body};
}

public type Todo record {
    # server-generated identifier
    string id;
    string title;
    boolean completed;
    string createdAt;
};

public type NewTodo record {
    string title;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type inline_response_200 record {
    # total matching todos
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Todo[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

# Any subset of a todo's mutable fields.
public type TodoUpdate record {
    string title?;
    boolean completed?;
};
